baseURL = 'https://barrcodes.dev/'
languageCode = 'en-us'
title = 'BarrCodes'
disableKinds = ['taxonomy', 'term']
enableRobotsTXT = true
cleanDestinationDir = true
[markup.highlight]
style = 'tokyonight-night'
[outputFormats.main-only]
mediaType = "text/html"
baseName = "main-only"
[outputFormats.head-only]
mediaType = "text/html"
baseName = "head-only"
[outputs]
home = ['html', 'main-only', 'head-only', 'rss']
section = ['html', 'main-only', 'head-only', 'rss']
page = ['html', 'main-only', 'head-only']
