baseURL = 'https://barrcodes.dev/'
languageCode = 'en-us'
title = 'BarrCodes'
disableKinds = ['taxonomy', 'term']
enableRobotsTXT = true

[permalinks]
posts = "/:slugorfilename/"
[markup]
[markup.highlight]
style = 'tokyonight-night'
